// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0UrzJ6zy1R6-T9cIq5FL2zPL3IYhhKo',
    appId: '1:1067266244076:web:fc811db3a5210ed14794c9',
    messagingSenderId: '1067266244076',
    projectId: 'chat-application-878e1',
    authDomain: 'chat-application-878e1.firebaseapp.com',
    databaseURL: 'https://chat-application-878e1-default-rtdb.firebaseio.com',
    storageBucket: 'chat-application-878e1.appspot.com',
    measurementId: 'G-VDY3E3JDKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDqmJlVhJgh8th2Dr_k8VHLJ_AAt4lf88',
    appId: '1:1067266244076:android:4290672f582dbc1f4794c9',
    messagingSenderId: '1067266244076',
    projectId: 'chat-application-878e1',
    databaseURL: 'https://chat-application-878e1-default-rtdb.firebaseio.com',
    storageBucket: 'chat-application-878e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATVehdb2OSB5pWQbzljqJ9Ubo9IZRzz6I',
    appId: '1:1067266244076:ios:0667462f6856785a4794c9',
    messagingSenderId: '1067266244076',
    projectId: 'chat-application-878e1',
    databaseURL: 'https://chat-application-878e1-default-rtdb.firebaseio.com',
    storageBucket: 'chat-application-878e1.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATVehdb2OSB5pWQbzljqJ9Ubo9IZRzz6I',
    appId: '1:1067266244076:ios:0667462f6856785a4794c9',
    messagingSenderId: '1067266244076',
    projectId: 'chat-application-878e1',
    databaseURL: 'https://chat-application-878e1-default-rtdb.firebaseio.com',
    storageBucket: 'chat-application-878e1.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO0UrzJ6zy1R6-T9cIq5FL2zPL3IYhhKo',
    appId: '1:1067266244076:web:4e985aafc9f8e4534794c9',
    messagingSenderId: '1067266244076',
    projectId: 'chat-application-878e1',
    authDomain: 'chat-application-878e1.firebaseapp.com',
    databaseURL: 'https://chat-application-878e1-default-rtdb.firebaseio.com',
    storageBucket: 'chat-application-878e1.appspot.com',
    measurementId: 'G-RX35T99Y2L',
  );
}
